# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e03e40b95f87594fa4bd4aa1ffd947c94024daf68174ee82ebfab3ffbfaa663323f10c37e5caa56c7f75b8ac7e1c2e5c7b63a888ce8892aa2b76c7774c23b77

test:
  secret_key_base: 2614ba36e081dd510af58b3858d84248573b4eeb9d999fda25600df74c6fdf60c15ad265019e2ca5abe1422275bda93f2ca585d1682b5b5f465df1ce836a67ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
